---
- hosts: servers
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: mattermost, tags: ['mattermost'] }
    - { role: matterbridge, tags: ['matterbridge'] }
    - { role: motd, tags: ['motd'] }
    - { role: docker, tags: ['docker'] }
    - { role: watchtower, tags: ['watchtower'] }
    - { role: directory, tags: ['directory'] }
